# This is a basic workflow to help you get started with Actions

name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: kmkfw/base

    steps:
      - uses: actions/checkout@v2
      - run: make test
